name: "dbt_workshop"
version: "1.0.0"
config-version: 2

profile: "default"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_workshop:
    bronze:
      +materialized: table
      bronze_citizens:
        +post-hook:
          - "GRANT SELECT ON {{ this }} TO data_engineer_role;"
    silver:
      +materialized: table
      # +grants:
      #   select:
      #     - data_analyst_role
    gold:
      +materialized: view # Materialized as views
      # +grants:
      #   select:
      #     - data_scientist_role
